### PR TITLE
Update alpine to 3.8

### PR DESCRIPTION
**Pull request by marians**
For https://github.com/giantswarm/giantswarm/issues/4197

### CODE REVIEW

**Comment by marians** [comment]
@MarcelMue Can you tell me where this is running?

**Comment by MarcelMue** [comment]
AFAIK it is used in in chart-operator e2e for sure. Uncertain if it is also used in guest clusters but I don't think so.

**Comment by marians** [comment]
I can't test this. Who can I assign this to for testing?

**Comment by MarcelMue** [comment]
As you can see in this project, your PR is the first one. There has only one person worked on this. I highly doubt anyone can really test this.

You can either close here or just merge and see if something breaks. Not sure how to progress otherwise.

**Comment by marians** [comment]
I see we did a great job with knowledge transfer ;-)

**Pull request merged**
